### ISSUE TITLE
fix please

### ISSUE THREAD

**Issue by NCPUser** [Kyza/BetterDiscordPlugins#14]
TypeError: Cannot read properties of undefined (reading 'default')
    at eval (betterdiscord://plugins/PlatformEmulator.plugin.js:334:36)
    at eval (betterdiscord://plugins/PlatformEmulator.plugin.js:510:5)
    at buildPlugin (betterdiscord://plugins/PlatformEmulator.plugin.js:512:4)
    at eval (betterdiscord://plugins/PlatformEmulator.plugin.js:517:2)
    at A.requireAddon (betterdiscord/renderer.js:4:35124)
    at A.loadAddon (betterdiscord/renderer.js:4:7625)
    at A.loadAddon (betterdiscord/renderer.js:4:32796)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:5617)

**Comment by TheVoidLeak** [comment]
I think this is no longer maintained. Hasn't been touched in 2 Years.
