### ISSUE TITLE
Could not be compiled

### ISSUE THREAD

**Issue by lighscent** [Kyza/BetterDiscordPlugins#15]
```md
## Discord Info
stable 277953 (2ff410b) Host 1.0.9037 x86 (45369) Windows 10 64-bit (10.0.19045)

## BetterDiscord
stable 1.10.1

### Plugins (12 Enabled):
- BDFDB (Enabled)
- ZeresPluginLibrary (Enabled)
- XenoLib (Enabled)
- APlatformIndicators
- Channel Permissions (Enabled)
- CustomStatusPresets (Enabled)
- DoNotTrack (Enabled)
- Hide Channels (Enabled)
- InvisibleTyping (Enabled)
- MessageLoggerV2 (Enabled)
- NoSpotifyPause (Enabled)
- PermissionsViewer (Enabled)
- PlatformEmulator
- SplitLargeMessages (Enabled)

### Themes (0 Enabled):

```

TypeError: Cannot read properties of undefined (reading 'getPlatform')
    at eval (betterdiscord://plugins/PlatformEmulator.plugin.js:334:44)
    at eval (betterdiscord://plugins/PlatformEmulator.plugin.js:510:5)
    at buildPlugin (betterdiscord://plugins/PlatformEmulator.plugin.js:512:4)
    at eval (betterdiscord://plugins/PlatformEmulator.plugin.js:517:2)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9469)
    at N.initialize (betterdiscord/renderer.js:5:3284)
    at N.initialize (betterdiscord/renderer.js:5:25573)
    at Object.startup (betterdiscord/renderer.js:5:408848)

**Comment by dxtintx** [comment]
same issue

**Comment by pp0236** [comment]
guys look at the latest commit date 😭

**Comment by lighscent** [comment]
a real dev never forgets to update

**Comment by a-catgirl-dev** [comment]
> a real dev never forgets to update

a real dev never updates
